#!/bin/bash

P="$(realpath "$1")"
DST="$(basename "$P").rr.tar"
TMP="$(basename "$P").rr.tmp"
REC="	For Recovery: See rr.tar on GitHub"
rm "$TMP" &> /dev/null
if [ ! -d "$P" ]; then
  P="$(dirname "$P")"
fi
tar --{owner,group}=1000 --numeric-owner --verbatim-files-from -cvf "$TMP" -C "$P" -T <(ls -A "$1") || exit 1
REC="$REC|$(sha256sum "$TMP" | cut -f1 -d' ')"
dd if=/dev/zero of="/tmp/$REC" bs=1M count=16 &> /dev/null
tar --{owner,group}=1000 --numeric-owner -rvf "$TMP" -C /tmp "$REC"
rm "/tmp/$REC"
rrtar "$TMP" && chmod -w "$TMP" && mv -f "$TMP" "$DST" || exit 1
